import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowDown, ArrowUpRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { BlueprintMark, TechnicalArt } from "@/components/site/technical-art";
import { ServicesList } from "@/components/site/services";
import { GeometricField } from "@/components/site/geometric-field";

export const Route = createFileRoute("/")({ head: () => ({ meta: [{ title: "ІБП — Інженерне проєктування" },{ name:"description",content:"Проєктування зовнішніх та внутрішніх інженерних мереж для житлових, громадських і промислових об’єктів." },{ property:"og:title",content:"ІБП — Інженерне проєктування" },{ property:"og:description",content:"Точні проєктні рішення для інженерних мереж будь-якої складності." },{ property:"og:type",content:"website" },{ name:"twitter:card",content:"summary_large_image" }] }), component: Home });
const process = [["Задача","Фіксуємо мету, склад робіт і очікуваний результат."],["Аналіз","Вивчаємо вихідні дані, обмеження та взаємозв’язки."],["Розрахунок","Виконуємо необхідні технічні розрахунки."],["Проєктування","Формуємо узгоджені інженерні рішення."],["Узгодження","Супроводжуємо передбачені завданням погодження."],["Готовий проєкт","Передаємо опрацьовану проєктну документацію."]];
const advantages = [["Якість","Уважне та відповідальне виконання проєктних робіт."],["Оперативність","Терміни визначаються індивідуально залежно від складності завдання."],["Доступна вартість","Вартість формується залежно від обсягу робіт, термінів, погоджень, експертизи та інших умов."],["Досвід","Фахівці бюро мають досвід виконання приватних та державних/бюджетних проєктів."]];
function Home(){
function moveDiagram(event: React.PointerEvent<HTMLElement>) {
  if (event.pointerType !== "mouse") return;
  const rect = event.currentTarget.getBoundingClientRect();
  event.currentTarget.style.setProperty("--pointer-x", `${((event.clientX - rect.left) / rect.width - 0.5) * 10}px`);
  event.currentTarget.style.setProperty("--pointer-y", `${((event.clientY - rect.top) / rect.height - 0.5) * 8}px`);
}
return <>
<section className="hero grid-surface" onPointerMove={moveDiagram}><div className="hero-grid"><TechnicalArt variant={2} animated className="hero-art"/></div><div className="shell hero-content"><div className="hero-kicker">Київ / Україна / з 2015 року</div><h1>Інженерне<br/>проєктування</h1><div className="hero-copy"><p>Проєктування зовнішніх та внутрішніх інженерних мереж будь-якої складності. Працюємо з житловими, громадськими та промисловими об’єктами на різних стадіях проєктування.</p><div className="hero-actions"><Button asChild size="lg" variant="technical"><Link to="/contact">Замовити проєкт <ArrowUpRight/></Link></Button><Button asChild size="lg" variant="technicalOutline"><Link to="/services">Наші послуги <ArrowDown/></Link></Button></div></div></div><div className="hero-coordinates">50.4501° N / 30.5234° E</div></section>
<section className="section section--compact"><div className="shell"><div className="section-heading-row"><div><div className="section-code">Інженерне бюро проєктів (ІБП) / з 2015 року</div><h2 className="section-title">Точність у кожному інженерному рішенні</h2></div><GeometricField variant={1} className="section-geometry" /></div><div className="fact-grid"><div className="fact"><strong>2015</strong><span>Рік заснування бюро</span></div><div className="fact"><strong>≈20</strong><span>Років досвіду засновника — головного інженера проєкту</span></div><div className="fact"><strong>СС3</strong><span>Сертифікація головного інженера проєкту</span></div><div className="fact"><strong>UA, KZ</strong><span>Працюємо по Україні та Казахстані</span></div></div></div></section>
<section className="section pt-0"><div className="shell"><div className="section-code">Спеціалізація / 12 напрямів</div><h2 className="section-title">Напрями проєктування</h2><ServicesList limit={6}/><div className="mt-8"><Button asChild variant="technicalOutline"><Link to="/services">Усі напрями <ArrowUpRight/></Link></Button></div></div></section>
<section className="focus-band"><div className="shell focus-grid"><div className="focus-copy"><div className="section-code">Основний фокус / 01</div><h2 className="mt-6">Газопостачання та котельні</h2><p>Один із основних напрямів роботи бюро. Формуємо взаємоузгоджені проєктні рішення на основі вихідних даних і вимог конкретного об’єкта.</p><small className="mt-8 block font-mono text-[10px] text-muted-foreground">СХЕМА Є ДЕКОРАТИВНОЮ ІЛЮСТРАЦІЄЮ, НЕ ТЕХНІЧНОЮ ДОКУМЕНТАЦІЄЮ</small></div><div className="focus-visual grid-surface"><TechnicalArt variant={0} animated/></div></div></section>
<section className="section pt-0"><div className="shell"><div className="section-heading-row"><div><div className="section-code">Процес / 01—06</div><h2 className="section-title">Як ми працюємо</h2></div><GeometricField variant={2} className="section-geometry" /></div><div className="process">{process.map(([title,desc],i)=><article className="process-step" key={title}><span>{String(i+1).padStart(2,"0")}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
<section className="section section--compact"><div className="shell"><div className="section-heading-row"><div><div className="section-code">Принципи / Факти</div><h2 className="section-title">Робота без зайвих обіцянок</h2></div><GeometricField variant={3} className="section-geometry" /></div><div className="advantages">{advantages.map(([title,desc],i)=><article className="advantage" key={title}><span>0{i+1}</span><h3>{title}</h3><p>{desc}</p></article>)}</div></div></section>
<section className="section"><div className="shell"><div className="section-code">Архів / Проєкти</div><h2 className="section-title">Проєктні матеріали</h2><div className="portfolio-placeholder"><div className="portfolio-visual grid-surface"><BlueprintMark className="w-48 opacity-50"/></div><div className="portfolio-copy"><div><h3 className="text-3xl">Структура підготовлена</h3><p className="mt-5">Реальні матеріали будуть додані після підготовки до публікації. Без вигаданих назв, об’єктів або характеристик.</p></div><div className="field-labels"><span>Фотографія / Назва</span><span>Тип об’єкта / Напрям</span><span>Опис / Креслення</span></div></div></div></div></section>
<section className="cta-band"><div className="shell"><div className="section-code">Новий проєкт / Контакт</div><h2 className="mt-6">Маєте задачу?<br/>Давайте її спроєктуємо.</h2><div className="button-row"><Button asChild size="lg" variant="technical"><Link to="/contact">Замовити проєкт <ArrowUpRight/></Link></Button></div></div></section>
</>}
